arxiv:
  ai: 0.6
  papers: 1.0
  research: 0.9
  science: 0.8
  education: 0.6
  technology: 0.5

astrophysics_data_system:
  astronomy: 1.0
  papers: 1.0
  research: 1.0

# deviantart:
#   art: 1.0

github:
  ai: 0.5
  code: 1.0
  tech: 0.7
  aimodels: 0.9
  datasets: 0.8

goodreads:
  books: 1.0
  mental health: 0.4

hackernews:
  news: 0.9
  tech: 0.8
  ai: 0.7
  startups: 0.6
  productivity: 0.5
  finance: 0.5

huggingface:
  ai: 1.0
  datasets: 0.9
  models: 0.9
  aimodels: 1.0
  technology: 0.6
  research: 0.5

imdb:
  movies: 1.0
  celebrity: 0.7

openstreetmap:
  location: 1.0
  maps: 1.0
  travel: 0.6

reddit:
  community: 1.0
  opinion: 0.9
  tech: 0.6
  pets: 0.6
  relationships: 0.8
  mental health: 0.7
  fashion: 0.5
  food: 0.5
  productivity: 0.5
  pschology: 0.6

steam:
  games: 1.0
  technology: 0.4

wikipedia:
  encyclopedia: 1.0
  research: 0.6
  science: 0.7
  history: 1.0
  economics: 0.8
  medicine: 0.8
  politics: 0.7
  mental health: 0.7
  climate: 0.6
  psychology: 0.6
  education: 0.6
  travel: 0.5
  food: 0.5
  celebrity: 0.4
